# fly.toml app configuration file generated for backend-rp25ew on 2025-05-22T06:07:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-rp25ew'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  memory = '256mb'
